install: skip
os: linux
dist: trusty
language: java
jdk: oraclejdk8


env:
  - TEST_CASE=./monolithic/ui_check
  - TEST_CASE=./monolithic/service/cart check
  - TEST_CASE=./monolithic/service/user check
  - TEST_CASE=./monolithic/repository/order check
  - TEST_CASE=./monolithic/repository/cart check
  - TEST_CASE=./monolithic/repository/product check
  - TEST_CASE=./monolithic/repository/user check

script:
  - ./gradlew clean jar

stages:
  - test

jobs:
  include:
    -stage: test
      -name: jacocoTestReport
      -install: skip
      -script:
        - find . jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
    -stage: test
      -name: ui_check
      install: skip
      -script:
        - COVERAGE=0.25 ./gradlew -p $TEST_CASE
      -env:
        TEST_CASE=./monolithic/ui_check
    -stage: test
      -name: cart_check
      -install: skip
      -script:
        - COVERAGE=0.25 ./gradlew -p $TEST_CASE
      -env:
        TEST_CASE=./monolithic/service/cart check
    -stage: test
      -name: user_check
      -install: skip
      -script:
        - COVERAGE=0.25 ./gradlew -p $TEST_CASE
      -env:
        TEST_CASE=./monolithic/service/user check
    -stage: test
      -name: order_check
      -install: skip
      -script:
        - COVERAGE=0.25 ./gradlew -p $TEST_CASE
      -env:
        TEST_CASE=./monolithic/repository/order check
    -stage: test
      -name: repo_cart_check
      -install: skip
      -script:
        - COVERAGE=0.25 ./gradlew -p $TEST_CASE
      -env:
        TEST_CASE=./monolithic/repository/cart check
    -stage: test
      -name: product_check
      -install: skip
      -script:
        - COVERAGE=0.25 ./gradlew -p $TEST_CASE
      -env:
        TEST_CASE=./monolithic/repository/product check
    -stage: test
      -name: repo_user_check
      -install: skip
      -script:
        - COVERAGE=0.25 ./gradlew -p $TEST_CASE
      -env:
        TEST_CASE=./monolithic/repository/user check



#script:
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
  #- find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
