install: skip
os: linux
dist: trusty
language: java
jdk: oraclejdk8


script:
  - ./gradlew clean jar

jobs:
    -name: jacocoTestReport
      - find . jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
    -name: ui_check
      - COVERAGE=0.25 ./gradlew -p ./monolithic/ui check
    -name: cart_check
      - COVERAGE=0.25 ./gradlew -p ./monolithic/service/cart check
    -name: user_check
      - COVERAGE=0.25 ./gradlew -p ./monolithic/service/user check
    -name: order_check
      - COVERAGE=0.25 ./gradlew -p ./monolithic/repository/order check
    -name: repo_cart_check
      - COVERAGE=0.25 ./gradlew -p ./monolithic/repository/cart check
    -name: product_check
      - COVERAGE=0.25 ./gradlew -p ./monolithic/repository/product check
    -name: repo_user_check
      - COVERAGE=0.25 ./gradlew -p ./monolithic/repository/user check



#script:
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
  #- find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
