install: skip
os: linux
dist: trusty
language: java
#jdk: oraclejdk8


env:
  - JDK_VERSION=oraclejdk8
  - JDK_VERSION=oraclejdk9
  - TEST_CASE=ui
  - TEST_CASE=service/cart
  - TEST_CASE=service/user
  - TEST_CASE=repository/order
  - TEST_CASE=repository/cart
  - TEST_CASE=repository/product
  - TEST_CASE=repository/user

jobs:
  include:
    - stage:
      jdk: $JDK_VERSION
      name: "JDK 9"
      script:
        - ./gradlew clean jar
      after_script:
        - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
        - COVERAGE=0.99 ./gradlew -p ./monolithic/$TEST_CASE check
      env:
        - JDK_VERSION=oraclejdk9
    - stage:
      jdk: $JDK_VERSION
      name: "JDK 8"
      script:
        - ./gradlew clean jar
      after_script:
        - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
        - COVERAGE=0.99 ./gradlew -p ./monolithic/$TEST_CASE check
      env:
        - JDK_VERSION=oraclejdk8





#script:
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
  #- find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
