install: skip
os: linux
dist: trusty
language: java
jdk: oraclejdk8


env:
  - TEST_CASE=ui
  - TEST_CASE=service/cart
  - TEST_CASE=service/user
  - TEST_CASE=repository/order
  - TEST_CASE=repository/cart
  - TEST_CASE=repository/product
  - TEST_CASE=repository/user

jobs:
  include:
  - name: "ui:0.25"
    env: TEST_CASE=ui COVERAGE=0.25
  - name: "service/cart:0.25"
    env: TEST_CASE=service/cart COVERAGE=0.25
  - name: "service/user:0.2"
    env: TEST_CASE=service/user COVERAGE=0.2
  - name: "repository/order:0.45"
    env: TEST_CASE=repository/order COVERAGE=0.15
  - name: "repository/cart:0.6"
    env: TEST_CASE=repository/cart COVERAGE=0.3
  - name: "repository/product:0.7"
    env: TEST_CASE=repository/product COVERAGE=0.7
  - name: "repository/user:0.6"
    env: TEST_CASE=repository/user COVERAGE=0.6

script:
  - ./gradlew clean jar

# after_success:
#   - ./gradlew check
#   - ./gradlew jacocoTestReport

after_script:
  - echo ${TEST_CASE}
  - echo ${COVERAGE}
  - COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/${TEST_CASE} check
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'





#script:
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
  #- find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
