install: skip
os: linux
dist: trusty
language: java
jdk: oraclejdk8


env:
  - TEST_CASE="COVERAGE=0.25 ./gradlew -p ./monolithic/ui check"
  - TEST_CASE="COVERAGE=0.25 ./gradlew -p ./monolithic/service/cart check"
  - TEST_CASE="COVERAGE=0.25 ./gradlew -p ./monolithic/service/user check"
  - TEST_CASE="COVERAGE=0.25 ./gradlew -p ./monolithic/repository/order check"
  - TEST_CASE="COVERAGE=0.25 ./gradlew -p ./monolithic/repository/cart check"
  - TEST_CASE="COVERAGE=0.25 ./gradlew -p ./monolithic/repository/product check"
  - TEST_CASE="COVERAGE=0.25 ./gradlew -p ./monolithic/repository/user check"

script:
  - ./gradlew clean jar

# after_success:
#   - ./gradlew check
#   - ./gradlew jacocoTestReport

after_script:
  - echo ${TEST_CASE}
  - ${TEST_CASE}
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'




#script:
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
  #- find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
