install: skip
os: linux
dist: trusty
language: java
jdk: oraclejdk8
services:
  -docker


env:
  matrix:
  - TEST_CASE=ui
  # - TEST_CASE=service/cart
  # - TEST_CASE=service/user
  # - TEST_CASE=repository/order
  # - TEST_CASE=repository/cart
  # - TEST_CASE=repository/product
  # - TEST_CASE=repository/user
  global:
  - secure: SyjFt8Ajwwb6+QztPWlPSSCy45FWF4mcECtX8sn5tPRb7XPH01On5QhPSLNNPuKx6la4iZ5LYQu1Y7rA+UwTgRiM0S/SoSYQRAsxQo4V7V1tfa2mqB+nDRyFaYQDWXHyOeQ4+whRX4S29MfpCTcB4BZrZ3SqF0MdysblHH7mGPb5YbOMZlMeq1n0LCeMzMH32kV8FVcPBi1bfM+xagYU7DxeQOtCWRSGEA1bP7FltEBz7ypWVfAjUt8oqbPhUqMcZlrYEloqOgch8KGJL2OO/JlSRVRK3RRCi/vdemhgGMAR/0QZ5SuoueZkrIaCpc7FU1ZmaQSraCHwFx5tSxE6/3lsZtxMJpXT58WnAHlK/J5sOJglodEMA4D5LXYbhzDR6NxmapdE2JZQOPRiDQio/DPIzXVdOM0IZuPiXMslPA/RMNuGpQuglrCtV3dvGnjuh5LhlhhrEasEFpy11YmYliIF1p3g/+65pJMKIOZViZeqJ21jB+dlBJN+m99kiI32lEWp11q2mKqu5r355VzSMXELdnx1vM3d0evOMXgouQKn7d9FmFCDTRrWiSSM4dHG68SaY/Iw0e7se4BqRmzB8t/F3eW7u15zxlIzbxQ5Fh57L5yxcl76sR6NN6VzsAYJPAY9BPLz+DAhjFa1ZnSMifBhk4q+6fp2IUQjiAiVWKw=
  - secure: eWA9ax1oErNv3xDB8g+tEf4JXbfylhHOBiyu/MwTi9igmgU/qOYAYGJS7buzh2L49Kqnbg5gq6067eTQkcLxiI6BrBmK7RQQdE9f1jxMwMAxI5fP5axd5XBuFhFRNQ4wCzV84KBBab+kl9Cap3j7NGZDbY9B7dHxPiOfyXP9KB5Q2yJR48ey9N/uE4o0TWogCIYdpIj4u+/rI53OxyQ2iQNXi4tXa1RR46ITUJfX+46TXDGCYpysYJQSy6E7F6SZXqH4ctjjK87x/zQDYVvfGs+iJVa6QdcY6Ot9ZmWJTW1bWweqY+5MRRAyYZo+sdqZ2g19/6nuno53jb7ru2YZbHBuBTkv8feEY0LYV1KnrnctEbIf2EjSQzg7LO9H41bVzcjuFormnjx4DYA+nK6Zwo0PfJM1gVELIchvqw8zEVALdxPBcpIO+Us+9J04mqpDEFTA+fYs89Za+Gi5pDDLjNPaq78VgPDvqJCjxxXoXStNCG0yejqbFYxhy3JdPig//YL2VLElIqYAZXUtk7wV8XLYR3T9Zmo3xYiFlv3hG8ohtRcH2NgtMpTWwdka8jxRcxGPukLMafdOdg9kXWHvOlFZT7z/2oWkVjQ6PoU6X1RBivazANBFTgxZoblGjO/1KzswBxn8fIIb2RsJbv9QzErDWfi7xvCzXjgjJ5mCqBA=
script:
- "./gradlew clean jar"
after_script:
- COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/${TEST_CASE} check
- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
