install: skip
os: linux
dist: trusty
language: java
jdk: oraclejdk8


env:
  - COVERAGE=1.0 TEST_CASE=ui
  - COVERAGE=1.0 TEST_CASE=service/cart
  - COVERAGE=1.0 TEST_CASE=service/user
  - COVERAGE=0.397 TEST_CASE=repository/order
  - COVERAGE=1.0 TEST_CASE=repository/cart
  - COVERAGE=1.0 TEST_CASE=repository/product
  - COVERAGE=1.0 TEST_CASE=repository/user


script:
  - ./gradlew clean jar

# after_success:
#   - ./gradlew check
#   - ./gradlew jacocoTestReport

after_script:
  - echo ${COVERAGE}
  - echo ${TEST_CASE}
  - COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/${TEST_CASE} check
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
  - echo $TRAVIS_TEST_RESULT


#script:
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
  #- find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
