os: linux
dist: trusty
language: java
jdk: oraclejdk8
services:
  - docker
env:
  matrix:
  - TEST_CASE=ui
  - TEST_CASE=service/cart
  # - TEST_CASE=service/user
  # - TEST_CASE=repository/order
  # - TEST_CASE=repository/cart
  # - TEST_CASE=repository/product
  # - TEST_CASE=repository/user
  global:
  - secure: SyjFt8Ajwwb6+QztPWlPSSCy45FWF4mcECtX8sn5tPRb7XPH01On5QhPSLNNPuKx6la4iZ5LYQu1Y7rA+UwTgRiM0S/SoSYQRAsxQo4V7V1tfa2mqB+nDRyFaYQDWXHyOeQ4+whRX4S29MfpCTcB4BZrZ3SqF0MdysblHH7mGPb5YbOMZlMeq1n0LCeMzMH32kV8FVcPBi1bfM+xagYU7DxeQOtCWRSGEA1bP7FltEBz7ypWVfAjUt8oqbPhUqMcZlrYEloqOgch8KGJL2OO/JlSRVRK3RRCi/vdemhgGMAR/0QZ5SuoueZkrIaCpc7FU1ZmaQSraCHwFx5tSxE6/3lsZtxMJpXT58WnAHlK/J5sOJglodEMA4D5LXYbhzDR6NxmapdE2JZQOPRiDQio/DPIzXVdOM0IZuPiXMslPA/RMNuGpQuglrCtV3dvGnjuh5LhlhhrEasEFpy11YmYliIF1p3g/+65pJMKIOZViZeqJ21jB+dlBJN+m99kiI32lEWp11q2mKqu5r355VzSMXELdnx1vM3d0evOMXgouQKn7d9FmFCDTRrWiSSM4dHG68SaY/Iw0e7se4BqRmzB8t/F3eW7u15zxlIzbxQ5Fh57L5yxcl76sR6NN6VzsAYJPAY9BPLz+DAhjFa1ZnSMifBhk4q+6fp2IUQjiAiVWKw=
  - secure: mgOpuuGEVmrcfPDx8y90mmqPouVNv91MMxCQQj5FG13+THW1P+s17Weh+BueR529g1/4X9ww3UvBLnELFDYOBJDAyhA7N3aIYW8kBK1fbvQhxbu6in9TE2CuFuJf1UTKrQVM98G5P78u+tNAZ1m+YsqzqcOxEvjK8wdt5/XPOfr7NhW+/yykxWDN3MXl9iYesF+MkG4+mzcTZtUCGTl/DwDeL33Xpdty0NYNezhI5UInfIBjD0kt4bJ4J9HCUOFcbn4ObSGBqCJrjh/KvmS2i3ApRC/axpQJ/vPbo0WqNiykJzHHAEtaZsuW9KX3DTjS5UoljMnRUQxurQMFboENJv3hxkL4lV6SDNRRCJbp5e3l42bKldA4upqjQ5T20DC45w1VdI/nhOMwKS7vVGyLzdV0LDNr5EAtWZJvwqlr2hVpoaPzget6OVI69R1qgxIZo/tiois+s59ry7QwnTUtHzHk2c6q0QxhGerybHBcmmhb6sk9e7xvHC/mpgnQoRq8XmyXoUAOyOw59KUxfY+LR8gQBnJTYAD591qUrvvsYkLUac3IrCPF6pegusbftN/fSSsLGOusSUQIbJq1Rp4aZMTaHXW8KBaBVVbh/X1KCHakceAEActp3Rc7qAelHuLReoOMttDWqZ3zFeQjs8648CtAKMSv3532XsheHBxY+MM=

install:
  - "./gradlew clean jar"

script:
  - COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/${TEST_CASE} check

after_script:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin"
  on:
    all_branches: true
