install: skip
os: linux
dist: trusty
language: java
jdk: oraclejdk8


env:
  - TEST_CASE=./monolithic/ui check
  - TEST_CASE=./monolithic/service/cart check
  - TEST_CASE=./monolithic/service/user check
  - TEST_CASE=./monolithic/repository/order check
  - TEST_CASE=./monolithic/repository/cart check
  - TEST_CASE=./monolithic/repository/product check
  - TEST_CASE=./monolithic/repository/user check


script:
  - ./gradlew clean jar


jobs:
  include:
  - name: "ui_check"
    env: TEST_CASE=./monolithic/ui check
  - name: "cart_check"
    env: - TEST_CASE=./monolithic/service/cart check
  - name: "user_check"
    env: - TEST_CASE=./monolithic/service/user check
  - name: "order_check"
    env: - TEST_CASE=./monolithic/repository/order check
  - name: "repo_cart_check"
    env: - TEST_CASE=./monolithic/repository/cart check
  - name: "prod_check"
    env: - TEST_CASE=./monolithic/repository/product check
  - name: "repo_user_check"
    env: - TEST_CASE=./monolithic/repository/user check


after_script:
  - find . jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
  - COVERAGE=0.25 ./gradlew -p $TEST_CASE




#script:
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
  #- find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
