install: skip
os: linux
dist: trusty
language: java
jdk: oraclejdk8
env:
  matrix:
  - TEST_CASE=ui
  - TEST_CASE=service/cart
  - TEST_CASE=service/user
  - TEST_CASE=repository/order
  - TEST_CASE=repository/cart
  - TEST_CASE=repository/product
  - TEST_CASE=repository/user
  global:
  - secure: O8MDaCqXcffs/rRyVz3GRLlHWmoQKPOq4bZA5gYLfuJ75ifMuEhBy7pdW6jf8kpG84cgp5/1XXa3/2+vVb/GQl73AbK457yvBPVeMN81ULoohahUj46sHAQ1ShorjgUZy3YTgu+6XbyUbFn5iRuNR5BjVxKZNBZI6GqUIjWA+TeB8NdZjX4rOgl/cWT82rSs16ZrFY/aNRLBKrypzSxF7j0FoJkz89mqfT51RTPiPu3JALhlUF4bJG3S8sPGxQz8ynr51kJi4WxMR1t8yRBz7QnIp8T6VLFhazZn15XfpC4ql3p3o3G5Osp0KNfZLKSC5LmgxdtQmQsis4uHbHWk+9Skznkdxro+hDgbjBbpZzCmyG1Wt0cPCdjz/cmiEMQXd21WtAGbit0iEXOEtvPj9NwaacMwC/McAE3nCGrqZ75W7L7DzwHmjUFBQ/AjwgCVjHFifZXsMDwLQS74sq4uxLorxpPx/DSW7rfmZD+Rk6bkiYqyxuovmdu8Lasu7uiXpU/c6zwhcSSCez5o1hZ4beBw+aWMsW+6VPgFtGYDxslw733KbAGuJADecKEQkOjAWUln21m3b7NFlZQ/GcDiqJOTiS6dZN1wHCp99k52OcXTbgS9u+c/3x/RlBbBSu7YcXg40oWtd6we2Hfu1+mVoQu4LLyPmniZ5OrwMkkYSpk=
  - secure: SyjFt8Ajwwb6+QztPWlPSSCy45FWF4mcECtX8sn5tPRb7XPH01On5QhPSLNNPuKx6la4iZ5LYQu1Y7rA+UwTgRiM0S/SoSYQRAsxQo4V7V1tfa2mqB+nDRyFaYQDWXHyOeQ4+whRX4S29MfpCTcB4BZrZ3SqF0MdysblHH7mGPb5YbOMZlMeq1n0LCeMzMH32kV8FVcPBi1bfM+xagYU7DxeQOtCWRSGEA1bP7FltEBz7ypWVfAjUt8oqbPhUqMcZlrYEloqOgch8KGJL2OO/JlSRVRK3RRCi/vdemhgGMAR/0QZ5SuoueZkrIaCpc7FU1ZmaQSraCHwFx5tSxE6/3lsZtxMJpXT58WnAHlK/J5sOJglodEMA4D5LXYbhzDR6NxmapdE2JZQOPRiDQio/DPIzXVdOM0IZuPiXMslPA/RMNuGpQuglrCtV3dvGnjuh5LhlhhrEasEFpy11YmYliIF1p3g/+65pJMKIOZViZeqJ21jB+dlBJN+m99kiI32lEWp11q2mKqu5r355VzSMXELdnx1vM3d0evOMXgouQKn7d9FmFCDTRrWiSSM4dHG68SaY/Iw0e7se4BqRmzB8t/F3eW7u15zxlIzbxQ5Fh57L5yxcl76sR6NN6VzsAYJPAY9BPLz+DAhjFa1ZnSMifBhk4q+6fp2IUQjiAiVWKw=
script:
- "./gradlew clean jar"
after_script:
- COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/${TEST_CASE} check
- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
